# Generated by Django 4.1.13 on 2024-08-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_1', models.IntegerField()),
                ('num_2', models.IntegerField()),
                ('result', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
