# Generated by Django 4.1.13 on 2024-08-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalysis', '0003_addition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='name',
        ),
    ]
