# Generated by Django 4.1.13 on 2024-08-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalysis', '0004_remove_addition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='date',
        ),
    ]
