version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  # frontend:
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile.nextjs
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./front-end/.env
  #   depends_on:
  #     django:
  #       condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"